config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "homes#index"
  resources :messages do
    resources :comments, only: :create
    resources :likes, only: [:create, :destroy]
  end
  resources :users, only: [:edit, :update, :show]
  resources :categories, only: [:show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :messages
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :message
  belongs_to :user
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :message
  validates_uniqueness_of :message_id, scope: :user_id
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :category
  has_many :comments
  has_many :likes, dependent: :destroy
  has_many :liked_users, through: :likes, source: :user
  validates :content, presence: true, unless: :image?
  mount_uploader :image, ImageUploader
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
          :recoverable, :rememberable, :validatable
  has_many :messages
  has_many :comments
  has_many :likes, dependent: :destroy
  has_many :liked_messages, through: :likes, source: :message
  #ユーザーが投稿に対して既にいいねしているか
  def already_liked?(message)
    likes.exists?(message_id: message.id)
  end
  validates :name, presence: true, uniqueness: true
  mount_uploader :image, ImageUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  # before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :image])
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def show
    @categories = Category.all
    categories = Category.find(params[:id])
    @messages = categories.messages
    @name = categories.name
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @comment = Comment.create(comment_params)
    @comment.user_id = current_user.id
    redirect_to "/messages/#{@comment.message.id}"
  end

  private
  def comment_params
    params.require(:comment).permit(:text).merge(user_id: current_user.id, message_id: params[:message_id])
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def index
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :set_message, only: [:create, :destroy]
  def create
    @like = current_user.likes.create(message_id: params[:message_id])
    redirect_to message_path(@message)
  end

  def destroy
    @like = Like.find_by(message_id: params[:message_id], user_id: current_user.id)
    @like.destroy
    redirect_to message_path(@message)
  end

  private
  def set_message
    @message = Message.find(params[:message_id])
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :set_current_user
  before_action :authenticate_user,{only: [:new,:create,:edit,:update]}
  before_action :set_message,{only: [:destroy,:edit,:update]}

  def index
    @message = Message.new
    @messages = Message.all
    @categories = Category.all
    @messages = Message.includes(:user).order("created_at DESC")
  end

  def new
    @message = Message.new
    @categories = Category.all
  end

  def create
    Message.create(message_params)
    redirect_to root_path
  end

  def destroy
    if @message.user_id = current_user.id
      @message.destroy
      render 'messages/destroy'
    else
      redirect_to root_path
    end
  end

  def edit
    @categories = Category.all
  end

  def update
    @message.update(message_params)
  end

  def show
    @categories = Category.all
    @message = Message.includes(:user).order("user.name DESC")
    @message = Message.find(params[:id])
    @comment = Comment.new
    @comments = @message.comments.includes(:user)
    @like = Like.new
    @name = User.find(@message[:user_id])
  end

  private
  def message_params
    params.require(:message).permit(:image, :content, :category_id).merge(user_id: current_user.id)
  end

  def set_message
    @message = Message.find(params[:id])
  end
  
  def set_current_user
    @current_user = User.find_by(id: session[:user_id])
  end
  
  def authenticate_user
    if !user_signed_in?
      redirect_to new_user_session_path
    end
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
def show
  @user = User.find(params[:id])
  @name = @user.name
  @messages = @user.messages
  @categories = Category.all
end

def edit
end

def update
  if current_user.update(user_params)
    redirect_to root_path
  else
    render :edit
  end
end

private
  def user_params
    params.require(:user).permit(:name, :image, :email, :password, :password_confirmation )
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/categories/show.html.haml
.contents
  .contents__title
    = @name
    の投稿一覧
.message
  = render "messages/message"

app/views/homes/index.html.haml
.one
.second
  .second__form
    .second__form__text
      %h2 foodie share time
      %p ー全国お取り寄せグルメ口コミサイトー
      %br
      %p あの味を、おうちでも。
      %p お気に入りのグルメをシェアして
      %p 食事から得る喜びが
      %p 広がりますように。
      %br
      %p 生産者、料理人の込めた思いが
      %p おうちに届き
      %p 幸せが広がりますように。
      %br
      %p 願いを込めて当サイトは誕生しました。
  .second__image
    = image_tag asset_path('sweets.jpg'), class: 'two'
  .third__image
    = image_tag asset_path('tsumami.jpg'), class: 'three'
  .forth__image
    = image_tag asset_path('wine.jpg'), class: 'four'
  .fifth__image
    = image_tag asset_path('present1.jpg'), class: 'five'
  .explain
    .explain__text
      %p 当サイトは完全無料で
      %p ご利用いただけます。
      %br
      %p お気に入りグルメのシェアタイムを
      %p お楽しみください。
      %br
      %p
        = link_to '▶︎ 新規登録する', new_user_registration_path
      %br
      %p
        = link_to '▶︎ ログインする', new_user_session_path
      %br
      %p
        = link_to '▶︎ 口コミ一覧ページはこちら', messages_path
.footer
  .footer__title
    = icon('fa', 'gift', class: 'icon')
    = link_to "foodie share time", root_path, class: "header__main__title"
    = icon('fa', 'truck', class: 'icon')

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title 
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body   
    .header
      .header__main
        .header__main__title
          = icon('fa', 'gift', class: 'icon')
          = link_to "foodie share time", root_path, class: "header__main__title"
          = icon('fa', 'truck', class: 'icon')
        .header__main__subtitle
          ー全国お取り寄せグルメ口コミサイトー
      .header__sub
        .header__sub__icon
          = link_to '口コミ一覧ページ', messages_path, class: 'index'
        .header__sub__menu    
          - if user_signed_in?
            = link_to "マイページ", "/users/#{current_user.id}", class: "post"
            = link_to "ログアウト", destroy_user_session_path, method: :delete, class: "post"
            = link_to  "投稿する", new_message_path, class: "post"
          - else
            = link_to "ログイン", new_user_session_path, class: 'post'
            = link_to "新規登録", new_user_registration_path, class: 'post'
    = yield

app/views/messages/_form.html.haml
.field
= form_for [@message] do |f|
  .field__list
    カテゴリー選択
    = f.collection_select(:category_id, @categories, :id, :name )
    = f.label :image, class: 'pic' do
      = f.file_field :image
    = f.text_area :content, cols: 30, rows: 8, class: 'text'
    = f.submit 'Send'

app/views/messages/_main_chat.html.haml
.main
  .categories
    .categories__list 
      Category
      - @categories.each do |category|
        .categories__list__name
          = link_to "#{category.name}", "/categories/#{category.id}", class: "tag"
  .message
    .message__info    
      .message__text
        .message__info__name
          - @messages.each do |message|
            = image_tag message.user.image, class: 'icon__image'
            = message.user.name
            - if message.content.present?
              .message__text__image
                = image_tag message.image.url, class: 'message__text__image' if message.image.present?
              .message__text__content
                = simple_format(message.content)
                .message__text__content__more
                  %ul.message__text__content__more__list
                  %li
                  = link_to '▶︎詳細', "/messages/#{message.id}",  method: :get, class: "select"
                  - if user_signed_in? && current_user.id == message.user_id
                    %li
                    = link_to '▶︎編集', "/messages/#{message.id}/edit", method: :get, class: "select"
                    %li
                    = link_to '▶︎削除', "/messages/#{message.id}", method: :delete, class: "select"

app/views/messages/_message.html.haml
.main
  .categories
    .categories__list 
      Category
      - @categories.each do |category|
        .categories__list__name
          = link_to "#{category.name}", "/categories/#{category.id}", class: "tag"
  .message
    .message__info    
      .message__text
        .message__info__name
          - @messages.each do |message|
            = image_tag message.user.image, class: 'icon__image'
            = message.user.name
            - if message.content.present?
              .message__text__image
                = image_tag message.image.url, class: 'message__text__image' if message.image.present?
              .message__text__content
                = simple_format(message.content)
                .message__text__content__more
                  %ul.message__text__content__more__list
                  %li
                  = link_to '▶︎詳細', "/messages/#{message.id}",  method: :get, class: "select"
                  - if user_signed_in? && current_user.id == message.user_id
                    %li
                    = link_to '▶︎編集', "/messages/#{message.id}/edit", method: :get, class: "select"
                    %li
                    = link_to '▶︎削除', "/messages/#{message.id}", method: :delete, class: "select"

app/views/messages/destroy.html.haml
.destroy
  .destroy__form
    削除が完了しました
  .top
  = link_to '▶︎トップにもどる', root_path, class: 'top'

app/views/messages/edit.html.haml
.edit
  .edit__form
    .edit__form__title
      .edit__form__title__name
        編集する
    .write__form__input  
      = render partial: "form"

app/views/messages/index.html.haml
.wrapper
  = render "main_chat"

app/views/messages/new.html.haml
.write
  .write__form
    .write__form__title
      .write__form__title__name
        投稿する
    .write__form__input
      = render partial: "form"

app/views/messages/show.html.haml
.main
  .categories
    .categories__list 
      Category
      - @categories.each do |category|
        .categories__list__name
          = link_to "#{category.name}", "/categories/#{category.id}", class: "tag"
  .message
    .message__info    
      .message__text
        .message__info__name
          = image_tag @message.user.image, class: 'icon__image'
          = @message.user.name
          .message__text__image
            = image_tag @message.image.url, class: 'message__text__image'
          .message__text__content
            = simple_format(@message.content)
            - if user_signed_in? && current_user.id == @message.user_id
              .message__text__content__more
                %ul.message__text__content__more__list
                %li
                = link_to '▶︎編集', "/messages/#{@message.id}/edit", method: :get, class: "select"
                %li
                = link_to '▶︎削除', "/messages/#{@message.id}", method: :delete, class: "select"
  .comments
    .comments__form
      Comment
      - if current_user
        = form_for [@message, @comment] do |f|
          = f.text_area :text, class: 'text', cols: 26, rows: 4
          = f.submit "SEND", class: "form__submit"
      - else
        %p ＊コメントの投稿には
        %p 新規登録/ログインが必要です
    .comments__list
      Comment List
      .comments__list__title
        - if @comments
          - @comments.each do |comment|
            = link_to comment.user.name, user_path(comment.user_id), class: "name"
            .comments__list__title__text
              = comment.text
      .likes__list
        %h3 いいね！リスト
        - if user_signed_in?
          - if current_user.already_liked?(@message)
            = link_to message_like_path(@message), method: :delete, remote: true do
              = icon('fas','heart')
            = @message.liked_users.count
          - else
            = link_to message_likes_path(@message), method: :post, remote: true do
              = icon('far', 'heart')
            = @message.liked_users.count
          - @message.liked_users.each do |user|
            %li= link_to user.name, user_path(id: user.id)
        - else
          %p ＊いいねには登録が必要です

app/views/messages/update.html.haml
.update
  .update__form
    更新しました
  .top
  = link_to '▶︎トップにもどる', root_path, class: 'top'

app/views/users/edit.html.haml
#account-page.account-page
  .account-page__inner.clearfix
    .account-page__inner--left.account-page__header
      %h2 Edit Account
      %h5 アカウントの編集
      = link_to "ログアウト", destroy_user_session_path, method: :delete, class: 'btn'
      = link_to "トップページに戻る", :back, class: 'btn'
    .account-page__inner--right.user-form
      = form_for(current_user) do |f|
        .field
          .field-label
            = f.label :name
          .field-input
            = f.text_field :name, autofocus: true
        .field
          .field-label
            = f.label :email
          .field-input
            = f.email_field :email
        .actions
          = f.submit "Update", class: 'btn'

app/views/users/show.html.haml
.contents
  .contents__title
    = @user.name
    さんの投稿一覧
.message
  = render "messages/message"